apiVersion: v1
kind: ConfigMap
metadata:
  name: abdm-proxy-njs-config
  labels:
    app: abdm-callback-proxy
    environment: default
data:
  njs.js: |-
    var delegateRepository = {
        Bahmni: 'dev.bahmnilite.in',
        IN2710015434: 'shreeclinic.bahmnilite.in',
        iplitclinic1: 'clinic1.bahmnilite.in',
        IPLitClinic2: 'clinic2.bahmnilite.in',
        iplitclinic3: 'clinic3.bahmnilite.in',
        deodharhospital: 'deodharhospital.bahmnilite.in',
        SandhuHospital: 'sandhuhospital.bahmni.in',
        'Get Well Polyclinic': 'getwellpolyclinic.bahmnilite.in',
        drbarvaliaclinic: 'drbarvaliaclinic.bahmnilite.in',
        IN0310001453: 'sukhveenhospital.bahmni.in',
        'IN2710000190': 'sukhveen-staging.bahmni.in'
    };

    function delegate(request: NginxHTTPRequest) {
      if (
        request.headersIn['X-HIU-ID'] &&
        delegateRepository.hasOwnProperty(request.headersIn['X-HIU-ID'].toString())
      ) {
        request.log(
          `routing for headersIn.X-HIU-ID: ${request.headersIn['X-HIU-ID']}`,
        );
        request.internalRedirect(
          `/delegate?delegate_url=${delegateUrl(
            request.uri,
            request.headersIn['X-HIU-ID'],
          )}`,
        );
      } else if (
        request.headersIn['X-HIP-ID'] &&
        delegateRepository.hasOwnProperty(request.headersIn['X-HIP-ID'].toString())
      ) {
        request.log(
          `routing for headersIn.X-HIP-ID: ${request.headersIn['X-HIP-ID']}`,
        );
        request.internalRedirect(
          `/delegate?delegate_url=${delegateUrl(
            request.uri,
            request.headersIn['X-HIP-ID'],
          )}`,
        );
      } else {
        request.log(`No heders matched - showing summary`);
        let summary: string;
        summary = 'JS summary\n\n';
        summary += 'Method: ' + request.method + '\n';
        summary += 'HTTP version: ' + request.httpVersion + '\n';
        summary += 'Host: ' + request.headersIn.host + '\n';
        summary += 'Remote Address: ' + request.remoteAddress + '\n';
        summary += 'URI: ' + request.uri + '\n';
    
        request.status = 200;
        request.headersOut['Content-Type'] = 'text/plain; charset=utf-8';
        request.sendHeader();
        request.send(summary);
    
        request.finish();
      }
}

function delegateUrl(requestUri: String, key: string): string {
  const delegatePath =
    delegateRepository[key] + requestUri.replace(/callback/i, 'hiprovider');

  return delegatePath;
}

export default { delegate };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abdm-callback-proxy
    environment: default
  name: abdm-callback-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abdm-callback-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abdm-callback-proxy
        environment: default
    spec:
      volumes:
        - name: abdm-proxy-njs-config
          configMap:
            name: abdm-proxy-njs-config
      containers:
        - image: infoiplitin/iplit-abdm-callback-proxy:latest
          name: iplit-abdm-callback-proxy
          volumeMounts:
            - name: abdm-proxy-njs-config
              mountPath: /etc/nginx/njs/njs.js
              subPath: njs.js
              readOnly: true
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: abdm-callback-proxy
spec:
  ports:
    - name: '9099'
      port: 9099
      targetPort: 80
  selector:
    app: abdm-callback-proxy
    environment: default
  type: NodePort
